# Generated by Django 4.1.6 on 2023-05-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newstype_newsitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.newstype'),
        ),
    ]
