# Generated by Django 4.1.6 on 2023-05-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'house_type',
                'verbose_name_plural': 'house_types',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField(default='', verbose_name='description')),
                ('published_at', models.DateTimeField(null=True, verbose_name='published_at')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='RoomsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(default=0, verbose_name='rooms')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(null=True, verbose_name='published_at')),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='home_sale.roomsquantity')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='home_sale.housetype')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'houses',
            },
        ),
    ]
